# Generated by Django 4.2.4 on 2023-08-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
    ]
